xtext -> diag state fragment
georgiana-ecobici/capella-textual-editor pull request #44
Opened 2020-10-02 07:00 UTC by MalinaStefaniaStoicanescu

Signed-off-by: MalinaStefaniaStoicanescu <malina.stoicanescu@thalesgroup.com>

2020-10-02 13:15 UTC, georgiana-ecobici requested changes
Undo formatting on all lines!

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>              }
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +  private static void editElements(Scenario scenario, List<EObject> elements) {
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +    List<EObject> previousStateFragments = new ArrayList<EObject>();
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +            previousStateFragments);
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>      }
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>    private static StateFragment createStateFragment(InteractionState interactionStateStart,
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>      return interactionState;
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
EDIT

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>      List<SequenceMessage> messagesToBeDeleted = sequenceMessages.stream()
DE AICI IN JOS, IN FISIERUL ASTA, nu mai e nicio modificare a mea

2020-10-02 13:28 UTC, MalinaStefaniaStoicanescu commented on plugins/org.polarsys.capella.scenario.editor/src/org/polarsys/capella/scenario/editor/helper/EmbeddedEditorInstanceHelper.java
>          .collect(Collectors.toList());
EDIT

2020-10-02 13:34 UTC, georgiana-ecobici commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
>      EList<SequenceMessage> sequenceMessages = scenario.getOwnedMessages();
What is the reason behind changing from EList to List?

2020-10-05 07:19 UTC, georgiana-ecobici approved these changes

2020-10-05 07:20 UTC, merged